"""scripts/kg/generate.py — regenerate notes/entities/*.md and notes/sources/*.md
from the compiled graph (build.compile_graph), per Spec 1 §3.3.

Generator ownership rule: this script owns notes/entities/ and notes/sources/
completely. It never invents identity data — entity-type/aliases/tier/authors
etc. are read back from each hub's own existing frontmatter (compile_graph
already does this), so a human editing those fields in Obsidian survives the
next regeneration. Only the derived body (backlinks, relations, cited-by) is
rebuilt every time. Files no longer referenced by the graph are never
silently deleted — they are moved to _to_delete/ and reported, exactly like
the vault's established convention for a session with no delete permission.
"""
import os, sys, re, json, argparse, glob
from datetime import date

sys.path.insert(0, os.path.dirname(__file__))
import parse as P
import build as B

# The clock must not be frozen at packaging time -- a hardcoded authoring
# date would stamp every generated hub note with the same `created:` forever.
TODAY = date.today().isoformat()


def yq(s):
    return json.dumps(str(s), ensure_ascii=False)


def flow_list(items):
    return "[" + ", ".join(yq(i) for i in items) + "]"


def existing_created(path):
    if os.path.exists(path):
        fm, _, _ = P.split_frontmatter(open(path, encoding="utf-8").read())
        if fm and fm.get("created"):
            return str(fm["created"])
    return TODAY


def render_entity_page(slug, entity, inbound, mentioned_in, created):
    etype = entity["type"]
    name = entity["name"]
    aliases = entity["aliases"] or [name]
    lines = [
        "---", "note-type: entity", f"entity-type: {etype}", f"entity: {slug}",
        f"title: {yq(name)}", f"aliases: {flow_list(aliases)}",
        f"tags: {flow_list(['entity', etype])}", f"created: {created}", "---", "",
        f"# {name}", "",
        "> [!info] Entity hub — generated by `kg generate` from the compiled graph.",
        "> Facts and citations live in the atomic notes linked below. `entity-type` and",
        "> `aliases` above are preserved across regeneration if you edit them in Obsidian;",
        "> everything from here down is rebuilt on every `kg build && kg generate`.",
        "",
    ]
    if entity.get("summary"):
        lines += [entity["summary"], ""]
    if inbound:
        lines += ["## Relations", ""]
        for predicate, items in sorted(inbound.items()):
            for subj_stem, subj_title in items:
                lines.append(f"- **{predicate}** ← [[{subj_stem}|{subj_title}]]")
        lines.append("")
    if mentioned_in:
        lines += [f"## Mentioned in ({len(mentioned_in)} notes)", ""]
        for stem, title in sorted(mentioned_in, key=lambda x: x[1]):
            lines.append(f"- [[{stem}|{title}]]")
        lines.append("")
    if not entity.get("summary") and etype == "unknown":
        lines += ["> [!warning] No identity data yet. This entity was referenced by a note but never "
                   "defined. Set `entity-type` above and add a summary paragraph here by hand — it will "
                   "be preserved.", ""]
    lines += ["---", "", "*Generated by `scripts/kg/generate.py`. Edit `entity-type`/`aliases` in the "
              "frontmatter or add a summary paragraph above the `## Relations` heading — both survive "
              "regeneration. Do not hand-edit the Relations/Mentioned-in sections; edit the atomic notes instead.*"]
    return "\n".join(lines) + "\n"


TIER_NOTE = {
    "primary": "First-party or official. Cite directly.",
    "analyst": "Established practitioner analyst with published methodology. Strong.",
    "journalism": "Named outlet with editorial standards.",
    "reference": "Encyclopedic — useful as an index into primary sources, not as the source.",
    "secondary": "Aggregation or SEO blog. Figures may well be right, but the methodology is not "
                 "published. Never present a figure from here as settled.",
}


def render_source_page(handle, src_fm, cited_by, created):
    tier = src_fm.get("tier", "secondary")
    title = src_fm.get("title", handle)
    lines = ["---", "note-type: source", f"handle: {handle}"]
    if src_fm.get("source-type"):
        lines.append(f"source-type: {src_fm['source-type']}")
    lines.append(f"title: {yq(title)}")
    lines.append(f"aliases: {flow_list(src_fm.get('aliases') or [f'Source: {handle}', handle])}")
    lines.append(f"tags: {flow_list(src_fm.get('tags') or ['source', f'source-{tier}'])}")
    if tier:
        lines.append(f"tier: {tier}")
    if src_fm.get("authors"):
        a = src_fm["authors"]
        lines.append(f"authors: {flow_list(a) if isinstance(a, list) else yq(a)}")
    elif src_fm.get("publisher"):
        lines.append(f"publisher: {yq(src_fm['publisher'])}")
    if src_fm.get("year"):
        lines.append(f"year: {src_fm['year']}")
    if src_fm.get("url"):
        lines.append(f"url: {yq(src_fm['url'])}")
    lines.append(f"created: {created}")
    lines += ["---", "", f"# {title}", ""]

    meta = []
    who = src_fm.get("authors") or src_fm.get("publisher")
    if who:
        who = ", ".join(who) if isinstance(who, list) else who
        meta.append(f'**{"Authors" if src_fm.get("authors") else "Publisher"}:** {who}')
    if src_fm.get("year"):
        meta.append(f'**Year:** {src_fm["year"]}')
    if src_fm.get("source-type"):
        meta.append(f'**Type:** {src_fm["source-type"]}')
    if meta:
        lines += ["  \n".join(meta), ""]
    if src_fm.get("url"):
        lines += [f'**Link:** <{src_fm["url"]}>', ""]

    lines += [f'> [!{"warning" if tier == "secondary" else "note"}] Credibility tier: **{tier}**',
              f'> {TIER_NOTE.get(tier, "")}', ""]
    if cited_by:
        lines += [f"## Cited by ({len(cited_by)} notes)", ""]
        for stem, t in sorted(cited_by, key=lambda x: x[1]):
            lines.append(f"- [[{stem}|{t}]]")
        lines.append("")
    lines += ["---", "", "*Generated by `scripts/kg/generate.py` from this note's own frontmatter "
              "(source-of-truth) plus every note that cites it. Edit the fields above directly — they "
              "are preserved. Do not hand-edit the Cited-by list.*"]
    return "\n".join(lines) + "\n"


# --- project vocabulary is configuration, not code -----------------------------
# Hardcoding a project's research angles here would mean the file could not be
# reused for another topic without editing the compiler. The blurbs come from
# `kg-config.json` at the vault root (written once at scaffold time, then
# hand-editable). A missing file, a missing key, or a malformed file is not an
# error — the map simply renders without blurbs.
def load_cluster_blurbs(root):
    path = os.path.join(root, "kg-config.json")
    try:
        with open(path, encoding="utf-8") as fh:
            cfg = json.load(fh)
    except (OSError, ValueError):
        return {}
    blurbs = cfg.get("angles") or cfg.get("cluster_blurbs") or {}
    if not isinstance(blurbs, dict):
        return {}
    return {str(k): str(v) for k, v in blurbs.items() if isinstance(v, str)}


def render_map(clusters, blurbs=None):
    lines = [
        "# Cluster Map", "",
        "Generated by `kg generate` from each note's first tag (the graph-color \"angle\").",
        "Hand-edit `index.md`'s \"Start here\" list for curated reading order instead — this",
        "file is a complete, always-current index, rebuilt every `kg build && kg generate`.",
        "",
    ]
    blurbs = blurbs or {}
    for tag in sorted(clusters):
        items = clusters[tag]
        lines.append(f"## {tag} ({len(items)} notes)")
        if tag in blurbs:
            lines.append("")
            lines.append(blurbs[tag])
        lines.append("")
        for stem, title in sorted(items, key=lambda x: x[1]):
            lines.append(f"- [[{stem}|{title}]]")
        lines.append("")
    lines += ["---", "", "*Generated by `scripts/kg/generate.py`. Do not hand-edit — edit tags on the "
              "atomic notes and regenerate.*"]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    root = args.root or P.vault_root()

    records, n_files, n_errors = P.parse_vault(root)
    if n_errors:
        print(f"REFUSING to generate: {n_errors} parse error(s).")
        return 1
    graph = B.compile_graph(records, root)
    by_stem = {r["stem"]: r for r in records}

    def title_of(stem):
        r = by_stem.get(stem)
        return (r["frontmatter"].get("title") if r else None) or stem

    # inbound relations per entity: {slug: {predicate: [(subj_stem, subj_title)]}}
    inbound = {}
    for rel in graph["relations"]:
        if rel["object"] in graph["entities"]:
            inbound.setdefault(rel["object"], {}).setdefault(rel["predicate"], [])
            item = (rel["subject"], title_of(rel["subject"]))
            if item not in inbound[rel["object"]][rel["predicate"]]:
                inbound[rel["object"]][rel["predicate"]].append(item)

    mentioned_in = {}
    for slug, e in graph["entities"].items():
        mentioned_in[slug] = [(stem, title_of(stem)) for stem in e["notes"]]

    # source cited-by: evidence-predicate relations targeting this handle + body wikilinks
    cited_by = {h: set() for h in graph["sources"]}
    for r in records:
        if r["note_type"] not in {"concept", "claim", "question"}:
            continue
        touched = {rel["target"] for rel in r["relations"] if rel["predicate"] == "evidence"}
        touched |= {wl["target"] for wl in r["body_wikilinks"] if wl["target"] in graph["sources"]}
        for h in touched:
            if h in cited_by:
                cited_by[h].add((r["stem"], title_of(r["stem"])))

    desired = {}
    ent_dir = os.path.join(root, "notes", "entities")
    for slug, e in graph["entities"].items():
        path = os.path.join(ent_dir, f"{slug}.md")
        created = existing_created(path)
        desired[path] = render_entity_page(slug, e, inbound.get(slug, {}), mentioned_in.get(slug, []), created)

    src_dir = os.path.join(root, "notes", "sources")
    for handle, s in graph["sources"].items():
        path = os.path.join(src_dir, f"{handle}.md")
        created = existing_created(path)
        desired[path] = render_source_page(handle, s, sorted(cited_by.get(handle, [])), created)

    existing_files = set(glob.glob(os.path.join(ent_dir, "*.md"))) | set(glob.glob(os.path.join(src_dir, "*.md")))
    stale = sorted(existing_files - set(desired))
    written = changed = 0
    for path, content in sorted(desired.items()):
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == content:
            continue
        changed += 1
        if not args.dry_run:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
        written += 1

    clusters = {}
    for r in records:
        if r["note_type"] not in {"concept", "claim", "question"}:
            continue
        tags = r["frontmatter"].get("tags") or []
        tag = tags[0] if tags else "(untagged)"
        clusters.setdefault(tag, []).append((r["stem"], title_of(r["stem"])))
    map_path = os.path.join(root, "map.md")
    map_content = render_map(clusters, load_cluster_blurbs(root))
    old_map = open(map_path, encoding="utf-8").read() if os.path.exists(map_path) else None
    if old_map != map_content:
        changed += 1
        if not args.dry_run:
            with open(map_path, "w", encoding="utf-8") as fh:
                fh.write(map_content)

    print(f"entity pages: {len(graph['entities'])}  source pages: {len(graph['sources'])}  + map.md")
    print(f"{'would write' if args.dry_run else 'wrote'}: {changed} changed / {len(desired)} total")
    if stale:
        print(f"stale (no longer referenced by the graph) — {'would move' if args.dry_run else 'moving'} to _to_delete/:")
        to_delete = os.path.join(root, "_to_delete")
        os.makedirs(to_delete, exist_ok=True)
        for path in stale:
            rel = os.path.relpath(path, root)
            print("  ", rel)
            if not args.dry_run:
                dest = os.path.join(to_delete, os.path.basename(path))
                if os.path.exists(dest):
                    dest = os.path.join(to_delete, f"{os.path.basename(path)}.dup{os.getpid()}")
                try:
                    os.rename(path, dest)
                except OSError as e:
                    print("    (could not move:", e, ")")
    return 0


if __name__ == "__main__":
    sys.exit(main())
